rules:
  - id: typescript-security-audit
    patterns:
      - pattern: eval(...)
    message: |
      Detected use of 'eval()'. This is dangerous as it can lead to code injection vulnerabilities.
    severity: ERROR
    languages: [typescript, javascript]
    
  - id: hardcoded-secrets
    patterns:
      - pattern-either:
          - pattern: password = "..."
          - pattern: api_key = "..."
          - pattern: secret = "..."
    message: |
      Hardcoded credentials detected. Use environment variables or secure secret management.
    severity: WARNING
    languages: [typescript, javascript]
